In [82]:
# Common Functions

#Numpy array to DataFrame
def Array2DataFrame(array):
    import numpy as np
    df = pd.DataFrame(data=array)
    return df

#Numpy array to DataFrame to SaveFile
def Array2SaveCSV(NpArray,filename='Delete'):
    import numpy as np
    df = pd.DataFrame(data=NpArray)
    df.to_csv(filename)


In [43]:
#Deep_Learning_Keras 
#1 Arch : how many layers Activation
#2 Compile :: loss and how it works
#3 Fit :: Froword and Back 
#4 Predict

#MIT Licensed

#Scale Data :: Getting data in to similar average value
 
#Regression       Y=f(x)
#Classification  Predictiong from set of descrete Options

#Deep Learning on Large Data Set

In [44]:
#1.1
#import
import numpy as np
import pandas
from keras.layers import Dense
from keras.models import Sequential

In [45]:
#1.2
#Import Data
df = pandas.read_csv('hourly_wages.csv')
predictors=np.delete(df.values,0,1) # Detete a Column  [1->column 0->row]
target=df.values[:,0]
n_cols = predictors.shape[1]

In [46]:
#1.3
#1 Arch

# Model 1)Sequential 2)  Check other models very complex connections  Very important   ??????????
model = Sequential()

# Dense :: All the Nodes in previous layers connect all the nodes in the current layer
model.add(Dense(100, activation= 'relu',input_shape=(n_cols,))) # (n_cols,) = any no of rows\data
model.add(Dense(100, activation='relu'))
model.add(Dense(1))

In [47]:
#1.4
#Compile
#2 Compile
#Optimizer Learing rate
#Adam is Best for Optimizer
#loss function Mean SquareError
model.compile(optimizer='adam', loss='mean_squared_error')

In [48]:
#1.5
#Fit
#Do Forword and Backword Propogation
model.fit(predictors, target)


Epoch 1/1
534/534 [==============================] - 98s 184ms/step - loss: 27.1264


In [49]:
#1.6
#prediction
model.predict(predictors[0:10])

array([[  8.48613453],
       [ 11.24972343],
       [  7.92303801],
       [  8.43539429],
       [ 10.4601059 ],
       [ 10.11528206],
       [ 10.028265  ],
       [  9.39352798],
       [ 12.23272514],
       [  9.39352798]], dtype=float32)

In [ ]:
#1.8 
#Saving 
model.save('model_hourly_wages.h5')


In [ ]:
#1.9
#Loading Model
my_model=load_model('model_hourly_wages.h5')

In [21]:
#1.10
#Check the Architure of Model
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 100)               1000      
_________________________________________________________________
dense_4 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 101       
Total params: 11,201
Trainable params: 11,201
Non-trainable params: 0
_________________________________________________________________


In [22]:
#1.11
# Print
print("Loss function: " + model.loss)


Loss function: mean_squared_error


In [2]:
#3
#Hourly_wages
import numpy as np
import pandas
from keras.layers import Dense
from keras.models import Sequential

#Import Data
df = pandas.read_csv('hourly_wages.csv')
predictors=np.delete(df.values,0,1) # Detete a Column  [1->column 0->row]
target=df.values[:,0] # or # df.wage_per_hour
n_cols = predictors.shape[1]

# Model
model = Sequential()
model.add(Dense(100, activation= 'relu',input_shape=(n_cols,))) 
model.add(Dense(100, activation='relu'))
model.add(Dense(1))

#compile
model.compile(optimizer='adam', loss='mean_squared_error')

#Fit
model.fit(predictors, target)

Epoch 1/1
534/534 [==============================] - 1s 1ms/step - loss: 50.6288


In [48]:
df.values
df.describe()
df.index
df.head()

wage_per_hour  union  education_yrs  experience_yrs  age  female  marr  \
0           5.10      0              8              21   35       1     1   
1           4.95      0              9              42   57       1     1   
2           6.67      0             12               1   19       0     0   
3           4.00      0             12               4   22       0     0   
4           7.50      0             12              17   35       0     1   

   south  manufacturing  construction  
0      0              1             0  
1      0              1             0  
2      0              1             0  
3      0              0             0  
4      0              0             0

In [8]:
#4
# Categorical
# Single -> Multi Column Convertion
from keras.utils import to_categorical
a=np.array([1,2,3])
cat1=to_categorical(a)
print(a)
print(cat1)

b=np.array([0,1,2,3])
cat2=to_categorical(b)
print("\n",b)
print(cat2)

c=np.array([0,1,2,13])
cat3=to_categorical(c)
print("\n",c)
print(cat3)

[1 2 3]
[[ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

 [0 1 2 3]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

 [ 0  1  2 13]
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [94]:
#5
# Classification 
# To Select from Bunch of Options
# Similar to Regression Only Few things are Different
# Loss function :: Categorical_crossentropy
# Log Loss
# Metric = ['accuracy'] Print accuracy at end of each epoch
# optimizer = 'sgd' 'adam'
# Output  Have Softmax activation  = Pridiction Sum to One  :: To Check Proabilities 

In [86]:
# 5
# Titanic
# sgd :: Stochastic Gradient descent
#Output  : Dead or Alive    Yes or No
import numpy as np
import pandas
from keras.layers import Dense
from keras.models import Sequential
from keras.utils import to_categorical

#Import Data
df = pandas.read_csv('Titanic_data.csv')
predictors=np.delete(df.values,0,1) # Detete a Column  [1->column 0->row]
target=to_categorical(df.survived)
pred_data=np.delete(pandas.read_csv('Titanic_pred_data.csv').values,0,1)
n_cols = predictors.shape[1]

#
model= Sequential()
model.add(Dense(32,activation='relu',input_shape=(n_cols,)))
model.add(Dense(2,activation='softmax')) # Output Survived or Died

#
model.compile(optimizer='sgd',loss='categorical_crossentropy',metrics=['accuracy'])

#
model.fit(predictors, target)

#
predictions = model.predict(pred_data)
probability_true =predictions

#Print
print("data\n",df.head(2))
print("\nPredictors\n",predictors[0])
print("\nTarget\n",target[0])
print("\nPredictors Shape\n",predictions.shape)
print("\nProbabilities of Survival\nYes  No\n",probability_true[0:2])

Epoch 1/1
891/891 [==============================] - 1s 2ms/step - loss: 2.5718 - acc: 0.6128
data
    survived  pclass   age  sibsp  parch     fare  male  age_was_missing  \
0         0       3  22.0      1      0   7.2500     1            False   
1         1       1  38.0      1      0  71.2833     0            False   

   embarked_from_cherbourg  embarked_from_queenstown  \
0                        0                         0   
1                        1                         0   

   embarked_from_southampton  
0                          1  
1                          0  

Predictors
 [3 22.0 1 0 7.25 1 False 0 0 1]

Target
 [ 1.  0.]

Predictors Shape
 (91, 2)

Probabilities of Survival
Yes  No
 [[  1.84627413e-06   9.99998212e-01]
 [  6.81351253e-10   1.00000000e+00]]


In [81]:
#6 Optimisation
# Smart Optimizer  'Adams'   'Stochastic graient descent SGD'
# Learning Rate
# Dying Nuron Problem i.e   NEURON -> 0  | No effect to out put |
# Vanishing gradiend i.e too low slopes updates almost to O | Ex tanhx function
# Lower value of loss function is Good

Unsupervised Instance Begin


In [90]:
#7 Learning Rates Different
# Titanic Data
from keras.optimizers import SGD # Import the SGD optimizer
import numpy as np
import pandas
from keras.layers import Dense
from keras.models import Sequential
from keras.utils import to_categorical

#Import Data
df = pandas.read_csv('Titanic_data.csv')
predictors=np.delete(df.values,0,1) # Detete a Column  [1->column 0->row]
target=to_categorical(df.survived)
pred_data=np.delete(pandas.read_csv('Titanic_pred_data.csv').values,0,1)
n_cols = predictors.shape[1]



lr_to_test = [.000001, 0.01, 1]

for lr in lr_to_test:
    print('\n\nTesting model with learning rate: %f\n'%lr )
    model= Sequential()
    model.add(Dense(32,activation='relu',input_shape=(n_cols,)))
    model.add(Dense(2,activation='softmax'))  
    my_optimizer = SGD(lr=lr) # Optimizear
    model.compile(optimizer=my_optimizer, loss='categorical_crossentropy',metrics=['accuracy'])
    model.fit(predictors, target)




Testing model with learning rate: 0.000001

Epoch 1/1
891/891 [==============================] - 154s 173ms/step - loss: 9.1388 - acc: 0.3737


Testing model with learning rate: 0.010000

Epoch 1/1
891/891 [==============================] - 2s 2ms/step - loss: 3.1238 - acc: 0.5825


Testing model with learning rate: 1.000000

Epoch 1/1
891/891 [==============================] - 2s 2ms/step - loss: 9.5846 - acc: 0.4018


In [92]:
#Validation split Data
#Split data as per percentage
#8
model.fit(predictors, target,validation_split=0.3)

Train on 623 samples, validate on 268 samples
Epoch 1/1
623/623 [==============================] - 0s 128us/step - loss: 9.7536 - acc: 0.3949 - val_loss: 10.3444 - val_acc: 0.3582


In [ ]:
#epochs
#Do Forword and backword Propogatin for Learning
#An epoch is one forward pass and one backward pass of all training examples
#One epoch consists of one full training cycle on the training set
#5 epochs as pybrain advice, the dataset will be divided into 5 subsets
#and the wights will update 5 times as maximum
#9
model.fit(predictors, target,validation_split=0.3,epochs=5)

In [99]:
#Early Stopping
#How many epoch before stopping training
#Call Early Stopping Through Callbacks  :: This take List as input
#9
from keras.callbacks import EarlyStopping
early_stopping_monitor = EarlyStopping(patience=3)
model.fit(predictors, target,validation_split=0.3, epochs=20,callbacks = [early_stopping_monitor])

Train on 623 samples, validate on 268 samples
Epoch 1/20
623/623 [==============================] - 0s 82us/step - loss: 9.7536 - acc: 0.3949 - val_loss: 10.3444 - val_acc: 0.3582
Epoch 2/20
623/623 [==============================] - 0s 64us/step - loss: 9.7536 - acc: 0.3949 - val_loss: 10.3444 - val_acc: 0.3582
Epoch 3/20
623/623 [==============================] - 0s 125us/step - loss: 9.7536 - acc: 0.3949 - val_loss: 10.3444 - val_acc: 0.3582
Epoch 4/20
623/623 [==============================] - 0s 48us/step - loss: 9.7536 - acc: 0.3949 - val_loss: 10.3444 - val_acc: 0.3582
