In [ ]:
#Deep_Learning_Keras 
#1 Arch : how many layers Activation
#2 Compile :: loss and how it works
#3 Fit :: Froword and Back 
#4 Predict

#MIT Licensed

#Scale Data :: Getting data in to similar average value
 
#Regression       Y=f(x)
#Classification  Predictiong from set of descrete Options

In [56]:
#1.1
#import
import numpy as np
import pandas
from keras.layers import Dense
from keras.models import Sequential

In [57]:
#1.2
#Import Data
df = pandas.read_csv('hourly_wages.csv')
predictors=np.delete(df.values,0,1) # Detete a Column  [1->column 0->row]
target=df.values[:,0]
n_cols = predictors.shape[1]

In [58]:
#1.3
#1 Arch

# Model 1)Sequential 2)  Check other models very complex connections  Very important   ??????????
model = Sequential()

# Dense :: All the Nodes in previous layers connect all the nodes in the current layer
model.add(Dense(100, activation= 'relu',input_shape=(n_cols,))) # (n_cols,) = any no of rows\data
model.add(Dense(100, activation='relu'))
model.add(Dense(1))

In [62]:
#1.4
#Compile
#2 Compile
#Optimizer Learing rate
#Adam is Best for Optimizer
#loss function Mean SquareError
model.compile(optimizer='adam', loss='mean_squared_error')

In [92]:
#1.5
#Fit
#Do Forword and Backword Propogation
model.fit(predictors, target)


Epoch 1/1
534/534 [==============================] - 0s 94us/step - loss: 19.7977


In [79]:
#1.6
#Print
print("Loss function: " + model.loss)

Loss function: mean_squared_error


In [73]:
#3
#Hourly_wages
import numpy as np
import pandas
from keras.layers import Dense
from keras.models import Sequential

#Import Data
df = pandas.read_csv('hourly_wages.csv')
predictors=np.delete(df.values,0,1) # Detete a Column  [1->column 0->row]
target=df.values[:,0] # or # df.wage_per_hour
n_cols = predictors.shape[1]

# Model
model = Sequential()
model.add(Dense(100, activation= 'relu',input_shape=(n_cols,))) 
model.add(Dense(100, activation='relu'))
model.add(Dense(1))

#compile
model.compile(optimizer='adam', loss='mean_squared_error')

#Fit
model.fit(predictors, target)

Epoch 1/1
534/534 [==============================] - 1s 1ms/step - loss: 45.4852


In [48]:
df.values
df.describe()
df.index
df.head()

wage_per_hour  union  education_yrs  experience_yrs  age  female  marr  \
0           5.10      0              8              21   35       1     1   
1           4.95      0              9              42   57       1     1   
2           6.67      0             12               1   19       0     0   
3           4.00      0             12               4   22       0     0   
4           7.50      0             12              17   35       0     1   

   south  manufacturing  construction  
0      0              1             0  
1      0              1             0  
2      0              1             0  
3      0              0             0  
4      0              0             0

In [120]:
#4
# Categorical
from keras.utils import to_categorical
a=np.array([1,2,3])
cat1=to_categorical(a)
print(cat1)

b=np.array([0,1,2,3])
cat2=to_categorical(b)
print("\n",cat2)

c=np.array([0,1,2,13])
cat3=to_categorical(c)
print("\n",cat3)

[[ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [94]:
#5
# Classification 
# To Select from Bunch of Options
# Similar to Regression Only Few things are Different
# Loss function :: Categorical_crossentropy
# Log Loss
# Metric = ['accuracy'] Print accuracy at end of each epoch
# optimizer = 'sgd' 'adam'
# Output  Have Softmax activation  = Pridiction Sum to One  :: To Check Proabilities 

In [115]:
# 4.1
# Titanic
# sgd :: Stochastic Gradient descent

import numpy as np
import pandas
from keras.layers import Dense
from keras.models import Sequential
from keras.utils import to_categorical

#Import Data
df = pandas.read_csv('Titanic_data.csv')
predictors=np.delete(df.values,0,1) # Detete a Column  [1->column 0->row]
target=to_categorical(df.survived)
n_cols = predictors.shape[1]

#
model= Sequential()
model.add(Dense(32,activation='relu',input_shape=(n_cols,)))
model.add(Dense(2,activation='softmax')) # Survived or Died

#
model.compile(optimizer='sgd',loss='categorical_crossentropy',metrics=['accuracy'])

#
model.fit(predictors, target)

Epoch 1/1
891/891 [==============================] - 1s 629us/step - loss: 3.9227 - acc: 0.5645


In [106]:
target

array([[ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.],
       ..., 
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.]])

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])