In [9]:
#Deep_Learning_Keras 
#1 Arch : how many layers Activation
#2 Compile :: loss and how it works
#3 Fit :: Froword and Back 
#4 Predict

#MIT Licensed

#Scale Data :: Getting data in to similar average value
 
#Regression       Y=f(x)
#Classification  Predictiong from set of descrete Options

In [10]:
#1.1
#import
import numpy as np
import pandas
from keras.layers import Dense
from keras.models import Sequential

In [11]:
#1.2
#Import Data
df = pandas.read_csv('hourly_wages.csv')
predictors=np.delete(df.values,0,1) # Detete a Column  [1->column 0->row]
target=df.values[:,0]
n_cols = predictors.shape[1]

In [12]:
#1.3
#1 Arch

# Model 1)Sequential 2)  Check other models very complex connections  Very important   ??????????
model = Sequential()

# Dense :: All the Nodes in previous layers connect all the nodes in the current layer
model.add(Dense(100, activation= 'relu',input_shape=(n_cols,))) # (n_cols,) = any no of rows\data
model.add(Dense(100, activation='relu'))
model.add(Dense(1))

In [13]:
#1.4
#Compile
#2 Compile
#Optimizer Learing rate
#Adam is Best for Optimizer
#loss function Mean SquareError
model.compile(optimizer='adam', loss='mean_squared_error')

In [14]:
#1.5
#Fit
#Do Forword and Backword Propogation
model.fit(predictors, target)


Epoch 1/1
534/534 [==============================] - 1s 2ms/step - loss: 58.0580


In [17]:
#1.6
#prediction
model.predict(predictors[0:10])

array([[  9.66553688],
       [ 15.44150448],
       [  7.3208952 ],
       [  7.89049339],
       [ 10.54580402],
       [  9.23855114],
       [ 12.20783901],
       [  8.95649052],
       [ 11.23385143],
       [  8.95649052]], dtype=float32)

In [ ]:
#1.8 
#Saving 
model.save('model_hourly_wages.h5')


In [ ]:
#1.9
#Loading Model
my_model=load_model('model_hourly_wages.h5')

In [21]:
#1.10
#Check the Architure of Model
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 100)               1000      
_________________________________________________________________
dense_4 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 101       
Total params: 11,201
Trainable params: 11,201
Non-trainable params: 0
_________________________________________________________________


In [22]:
#1.11
# Print
print("Loss function: " + model.loss)


Loss function: mean_squared_error


In [73]:
#3
#Hourly_wages
import numpy as np
import pandas
from keras.layers import Dense
from keras.models import Sequential

#Import Data
df = pandas.read_csv('hourly_wages.csv')
predictors=np.delete(df.values,0,1) # Detete a Column  [1->column 0->row]
target=df.values[:,0] # or # df.wage_per_hour
n_cols = predictors.shape[1]

# Model
model = Sequential()
model.add(Dense(100, activation= 'relu',input_shape=(n_cols,))) 
model.add(Dense(100, activation='relu'))
model.add(Dense(1))

#compile
model.compile(optimizer='adam', loss='mean_squared_error')

#Fit
model.fit(predictors, target)

Epoch 1/1
534/534 [==============================] - 1s 1ms/step - loss: 45.4852


In [48]:
df.values
df.describe()
df.index
df.head()

wage_per_hour  union  education_yrs  experience_yrs  age  female  marr  \
0           5.10      0              8              21   35       1     1   
1           4.95      0              9              42   57       1     1   
2           6.67      0             12               1   19       0     0   
3           4.00      0             12               4   22       0     0   
4           7.50      0             12              17   35       0     1   

   south  manufacturing  construction  
0      0              1             0  
1      0              1             0  
2      0              1             0  
3      0              0             0  
4      0              0             0

In [8]:
#4
# Categorical
# Single -> Multi Column Convertion
from keras.utils import to_categorical
a=np.array([1,2,3])
cat1=to_categorical(a)
print(a)
print(cat1)

b=np.array([0,1,2,3])
cat2=to_categorical(b)
print("\n",b)
print(cat2)

c=np.array([0,1,2,13])
cat3=to_categorical(c)
print("\n",c)
print(cat3)

[1 2 3]
[[ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

 [0 1 2 3]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

 [ 0  1  2 13]
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [94]:
#5
# Classification 
# To Select from Bunch of Options
# Similar to Regression Only Few things are Different
# Loss function :: Categorical_crossentropy
# Log Loss
# Metric = ['accuracy'] Print accuracy at end of each epoch
# optimizer = 'sgd' 'adam'
# Output  Have Softmax activation  = Pridiction Sum to One  :: To Check Proabilities 

In [53]:
# 4.1
# Titanic
# sgd :: Stochastic Gradient descent
#Output  : Dead or Alive    Yes or No
import numpy as np
import pandas
from keras.layers import Dense
from keras.models import Sequential
from keras.utils import to_categorical

#Import Data
df = pandas.read_csv('Titanic_data.csv')
predictors=np.delete(df.values,0,1) # Detete a Column  [1->column 0->row]
target=to_categorical(df.survived)
n_cols = predictors.shape[1]

#
model= Sequential()
model.add(Dense(32,activation='relu',input_shape=(n_cols,)))
model.add(Dense(2,activation='softmax')) # Survived or Died

#
model.compile(optimizer='sgd',loss='categorical_crossentropy',metrics=['accuracy'])

#
model.fit(predictors, target)

#
predictions = model.predict(predictors)
probability_true =predictions[:,1]
print(predictions.shape)
print(probability_true)

Epoch 1/1
891/891 [==============================] - 1s 896us/step - loss: 2.7872 - acc: 0.6117
(891, 2)
[  1.28296968e-02   1.11328884e-08   1.27289444e-02   1.36248514e-06
   1.86100265e-03   3.09178862e-03   4.19693521e-07   8.00135825e-03
   9.38659348e-03   3.82701925e-04   2.51540113e-02   2.67345877e-05
   1.95582770e-02   1.35726135e-04   7.55440593e-02   1.09958426e-04
   1.75570382e-03   4.28271433e-03   2.15733796e-03   4.86527942e-03
   2.91439239e-04   1.79373124e-03   3.83989811e-02   4.89191407e-05
   9.31888726e-03   2.09537786e-04   2.91590509e-03   9.12166102e-29
   5.27806301e-03   5.50796837e-03   8.57923515e-05   4.00982512e-16
   5.30519243e-03   1.12567623e-05   1.23638255e-09   3.86160792e-07
   2.91541987e-03   1.66780539e-02   5.03538223e-03   1.94998458e-02
   1.17231754e-03   1.69791630e-03   2.83911917e-03   2.16671266e-04
   2.19660401e-02   5.47437137e-03   1.52767706e-03   5.30519243e-03
   4.51396481e-04   6.52429787e-03   9.12567266e-05   1.67955663e-0

In [46]:
predictors[1]

array([1, 38.0, 1, 0, 71.2833, 0, False, 1, 0, 0], dtype=object)

In [39]:
target



array([[ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.],
       ..., 
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.]])