In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV



# from keras.layers import Dense
# pred=np.loadtxt('MinMax_Data1.csv',delimiter=',')
data=pd.read_csv('MinMax_Data1.csv')
print (data.head())
X=data.drop(['OUTCOME','STATUS_X','STATUS_O','INTILLEGENCE_X','INTILLEGENCE_O'],axis=1).values
Y=data['OUTCOME'].values
# print(data.head())
# print(X)
# print(Y)
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1,random_state=42)
reg=LogisticRegression()


reg.fit(X_train,Y_train)
y_pred=reg.predict(X_test)
print(y_pred)
print(Y_test)
reg.score(X_test,Y_test)




   X1  X2  X3  X4  X5  X6  X7  X8  X9  OUTCOME  STATUS_X  STATUS_O  \
0   0   0   3   0   1   0   0   0   0        1       NaN       NaN   
1   3   1   3   0   1   0   0   0   0        8       NaN       NaN   
2   3   1   3   1   1   0   0   3   0        6       NaN       NaN   
3   3   1   3   1   1   3   0   3   1        7       NaN       NaN   

   INTILLEGENCE_X  INTILLEGENCE_O  
0              10              10  
1              10              10  
2              10              10  
3              10              10  
[6]
[8]


0.0

In [ ]:
Game_Matrix=np.chararray((3,3),unicode=True)
print (Game_Matrix)
while True:
    X=int(input())
    Y=int(input())
    Game_Matrix[X-1,Y-1]='O'
    MAT1=convertion_data_num(Game_Matrix)
    print(MAT1[0,0])
    X_TESTR=z=np.array([MAT1[0,0],MAT1[0,1],MAT1[0,2]  ,MAT1[1,0],MAT1[1,1],MAT1[1,2]   ,MAT1[2,0],MAT1[2,1],MAT1[2,2]])
    print (X_TESTR)
    cy_pred=reg.predict(X_TESTR)
    ML=convertion_best_1_9_X_Y(cy_pred[0])
    print ("ML :", ML)
    Game_Matrix[ML[0],ML[1]]='X'
    print(Game_Matrix)
    # print (convertion_best_1_9_X_Y(cy_pred[0]))



    


[['' '' '']
 ['' '' '']
 ['' '' '']]
1
1


C:\Users\midas\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


3
[3 0 0 0 0 0 0 0 0]
ML : [1 2]
[['O' '' '']
 ['' '' 'X']
 ['' '' '']]
1
3


C:\Users\midas\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


3
[3 0 3 0 0 1 0 0 0]
ML : [2 0]
[['O' '' 'O']
 ['' '' 'X']
 ['X' '' '']]
3
3


C:\Users\midas\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


3
[3 0 3 0 0 1 1 0 3]
ML : [2 0]
[['O' '' 'O']
 ['' '' 'X']
 ['X' '' 'O']]


In [2]:
def convertion_data_num( board=np.chararray((3,3),unicode=True)):
    board
    OP=np.arange(9).reshape(3,3)
    OP[:]=999
    for i in range(0,3):
        for j in range(0,3):
            if (board[i][j]=='X'): 
                OP[i][j]=1
            if (board[i][j]=='O'): 
                OP[i][j]=3
            if (board[i][j]==''): 
                OP[i][j]=0
    return OP
def convertion_best_1_9_X_Y(X):
    if (X==1):
        return np.array([0,0])
    elif(X==2):
        return np.array([0,1])
    elif(X==3):
        return np.array([0,2])
    elif (X==4):
        return np.array([1,0])
    elif(X==5):
        return np.array([1,1])
    elif(X==6):
        return np.array([1,2])
    elif (X==7):
        return np.array([2,0])
    elif(X==8):
        return np.array([2,1])
    elif(X==9):
        return np.array([2,2])

In [1]:
import keras as k
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))



Using TensorFlow backend.


b'Hello, TensorFlow!'


In [48]:
from bs4 import BeautifulSoup

import requests
url="www.pythonforbeginners.com/python-on-the-web/web-scraping-with-beautifulsoup/"
r  = requests.get("http://" +url)
data = r.text
soup = BeautifulSoup(data)
for link in soup.find_all('a'):
    print (link)
    print (" ")
    
    print(link.get('href'))

C:\Users\midas\Anaconda3\lib\site-packages\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file C:\Users\midas\Anaconda3\lib\runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))


<a class="navbar-brand" href="/" title="pythonforbeginners.com">
<img alt="pythonforbeginners.com" src="/static/img/pfb_logo.png"/>
</a>
/
<a href="/" title="Home">Home</a>
/
<a href="/learn-python/" title="Learn Python">Learn Python</a>
/learn-python/
<a href="/basics/" title="Basics">Basics</a>
/basics/
<a href="/lists/" title="lists">Lists</a>
/lists/
<a href="/dictionary/" title="dictionary">Dictionary</a>
/dictionary/
<a href="/code-snippets-source-code/" title="code snippets">Code Snippets</a>
/code-snippets-source-code/
<a href="/modules-in-python/" title="modules">Modules</a>
/modules-in-python/
<a href="/">Home</a>
/
<a href="/python-on-the-web/" title="Web &amp; Internet"><span class="glyphicon glyphicon-folder-open"></span>  Web &amp; Internet</a>
/python-on-the-web/
<a href="http://www.crummy.com/software/BeautifulSoup/" target="_blank" title="bs4">Beautiful Soup 4</a>
http://www.crummy.com/software/BeautifulSoup/
<a href="http://docs.python-requests.org/en/latest/" target=

In [19]:
print (soup)

<!DOCTYPE html>
<html lang="en-US" prefix="og: http://ogp.me/ns#">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width" name="viewport"/>
<title>Web Scraping with BeautifulSoup</title>
<link href="http://gmpg.org/xfn/11" rel="profile"/>
<link href="http://www.pythonforbeginners.com/python-on-the-web/web-scraping-with-beautifulsoup/" rel="canonical"/>
<meta content="en_US" property="og:locale"/>
<meta content="website" property="og:type"/>
<meta content="Web Scraping with BeautifulSoup" property="og:title"/>
<meta content="http://www.pythonforbeginners.com/python-on-the-web/web-scraping-with-beautifulsoup/" property="og:url"/>
<meta content="Python For Beginners" property="og:site_name"/>
<link href="http://www.pythonforbeginners.com/feed/" rel="alternate" title="Python For Beginners » Feed" type="application/rss+xml"/>
<meta content=' Web Scraping "Web scraping (web harvesting or web data extraction) is a computer software technique of extracting information from websites.

In [2]:
import serial

ModuleNotFoundError: No module named 'serial'